version: "3"
services:
  server:
    image: m2
    ports:
      - "8081:8081"
    networks:
      - server-client
    depends_on:
      - client
  client:
    image: m1
    ports:
    - "8080:8080"
    networks:
      - server-client
networks:
  server-client: